<script src="{{ asset('assets/public/js/vendor/modernizr-3.5.0.min.js') }}"></script>
<script src="{{ asset('assets/public/js/vendor/jquery-1.12.4.min.js') }}"></script>
<script src="{{ asset('assets/public/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/public/js/bootstrap.min.js') }}"></script>
{{-- <script src="{{ asset('assets/public/js/one-page-nav-min.js') }}"></script>
<script src="{{ asset('assets/public/js/slick.min.js') }}"></script>
<script src="{{ asset('assets/public/js/ajax-form.js') }}"></script>
<script src="{{ asset('assets/public/js/paroller.js') }}"></script>
<script src="{{ asset('assets/public/js/wow.min.js') }}"></script>
<script src="{{ asset('assets/public/js/js_isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/public/js/imagesloaded.min.js') }}"></script>
<script src="{{ asset('assets/public/js/parallax.min.js') }}"></script>
<script src="{{ asset('assets/public/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('assets/public/js/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('assets/public/js/jquery.scrollUp.min.js') }}"></script>
<script src="{{ asset('assets/public/js/parallax-scroll.js') }}"></script>
<script src="{{ asset('assets/public/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('assets/public/js/element-in-view.js') }}"></script> --}}
<script src="{{ asset('assets/public/js/main.js') }}"></script>
